name: Publish Playwright Canary

on:
  push:
    branches:
      - main
    paths:
      - "e2e/**"

  # This is for testing purposes only, should be removed
  pull_request:
    branches:
      - main
    paths:
      - "e2e/**"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@742a180fa47f3adfb5115902ae4955acc6ad769b # v4
        with:
          name: flanksource/flanksource-ui-playwright-canary
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          tags: "latest, ${{ github.sha }}"
          workdir: e2e
